### ISSUE TITLE
t2i training problem

### ISSUE THREAD

**Issue by sunmeng7** [Stability-AI/stablediffusion#225]
![image](https://user-images.githubusercontent.com/50901976/228525420-dbdaee8f-9612-414c-8e7f-0bb37fb308d3.png)
I train the diffusion stage using my own dataset, but the sampling results are above.
How can I solve it?

My config as follows:

```
model:
  base_learning_rate: 1.0e-4
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 32
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        use_checkpoint: True
        use_fp16: False
        image_size: 256
        in_channels: 4
        out_channels: 4
        model_channels: 128
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 64
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ckpt_path: 'logs/2023-03-23_autoencoder_kl_32x32x4/checkpoints/epoch=000028.ckpt'
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenOpenCLIPEmbedder
      params:
        freeze: True
        layer: "penultimate"
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 0
    wrap: false
    train:
      target: ldm.data.imagenet3.MutilVox
      params:
        size: 256
        split: "train"
    validation:
      target: ldm.data.imagenet3.MutilVox
      params:
        size: 256
        split: "valid"

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000 
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
```
